"""create patients table

Revision ID: c36b8c93d966
Revises: 
Create Date: 2026-02-21 14:02:24.171701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c36b8c93d966'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_patients_background_gin'), table_name='patients', postgresql_using='gin')
    op.drop_index(op.f('idx_patients_current_assessment_gin'), table_name='patients', postgresql_using='gin')
    op.drop_index(op.f('idx_patients_nurse_gin'), table_name='patients', postgresql_using='gin')
    op.drop_index(op.f('idx_patients_patient_info_gin'), table_name='patients', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_patients_patient_info_gin'), 'patients', ['patient_info'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_patients_nurse_gin'), 'patients', ['nurse'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_patients_current_assessment_gin'), 'patients', ['current_assessment'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_patients_background_gin'), 'patients', ['background'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###
